//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appium.Integration.Tests.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Appium.Integration.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ApiDemos_debug {
            get {
                object obj = ResourceManager.GetObject("ApiDemos_debug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PathToLinuxNode {
            get {
                object obj = ResourceManager.GetObject("PathToLinuxNode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PathToMacOSNode {
            get {
                object obj = ResourceManager.GetObject("PathToMacOSNode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PathToWindowsNode {
            get {
                object obj = ResourceManager.GetObject("PathToWindowsNode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] selendroid_test_app_0_10_0 {
            get {
                object obj = ResourceManager.GetObject("selendroid_test_app_0_10_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TestApp7_1_app {
            get {
                object obj = ResourceManager.GetObject("TestApp7_1_app", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UICatalog7_1_app {
            get {
                object obj = ResourceManager.GetObject("UICatalog7_1_app", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WebViewApp7_1_app {
            get {
                object obj = ResourceManager.GetObject("WebViewApp7_1_app", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IntentExample {
            get {
                object obj = ResourceManager.GetObject("IntentExample", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
